version: '3.4'

services:
  basketdb:
    image: redis
    ports:
      - '6379:6379'
  basketmicroservice:
    image: basketmicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
